dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.8.3"
  - "Uniswap/v3-periphery@1.3.0"
  - "Uniswap/v3-core@1.0.0"

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3"
      - "@uniswap-v3-periphery=Uniswap/v3-periphery@1.3.0"
      - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
